# Number -> int , float , complex -> 34i+3 
# Boolean -> True , False  Built-in function-type()
quantity = 23
print (type(quantity))
# Sequence -> Ordered collection of items
# List -> sequence of itmes separated by commas and enclosed in sequare bracket[5,33.4,"New delhi","2a"] It contain different types of data. it can be changed.
list = [3,46,"k","3.8",'kk']
print(list)
# Touple -> sequence of itmes separated by commas and enclosed in paranthesis (10,34,"Apple",4.2,'a') It contain different types of data. But it does not change after created.
touple = (10,45,"apple",4.5,'a')
print(touple)
# String -> group of character.
str = "khushi sharma"
print(str)
# Mapping -> Mapping is an unordered data type in python.
# Dictionary -> Dictionary in python holds data items in key-value pairs and items are enclosed in curley bracket {}  access data fastly , every key is separated from its value using a colon(:)sign. >>> dict1 = {'fruits': 'Apple', 'Climate':'cold'}
dict1 = {'fruits': 'Apple', 'Climate':'cold'}
print(dict1['fruits'])
