#FUNCTION is set of statement or instructions.
# ARGUMENTS - While calling a fuction , we may pass value(s) , called arguments.
# RETURN VALUE - A function may or may not return one or more values.
# input() , print() , bool() , chr() , tuple() , abs() , divmod() , max() , min() , pow() , sum() , len() , range() , type() , str(), dict() , float() , int() , ord() , list() , set().
#CALCULATE THE SQUARE OF THE NUMBER
num = int(input("enter the number"))
square = num*num 
print(square)

